#!/etc/bash

#text configs. To make nice colorfull and bold text.
count=1
red="\e[31m"
green="\e[32m"
purple="\e[35m"
cyan="\e[36m"
yellow="\e[33m"
blank="\e[0m"

bold=$(tput bold)
normal=$(tput sgr0)

tag=(
  '@JustCallMeDullp'
  '@duløjshdlfsdf-jkdsobyfcitskjfjnhecaoiolfx-cueyfdghrhaneslkdxreokjurfkjjihulp'
  '@dulup'
  '@qnlnb'
  '@qulub'
)

#the next comment is old and wrong. But i'm too lazy to remove it.
#this one look scary, but it's just cutting the result of running "ifcinfig eno1" to only display the ip
#network=$(ifconfig eno1 | grep "inet " | cut -d " " -f 10) # <--- This only woks with "net-tools" and olnly if you're using eno1. not practical
network=$(ip route get 1.1.1.1 | grep -oP "src \K\S+") # This is supposed to see what you use, Like: eth0, wlan0, enp3s0,

# This is the ASCII banners
bigtext=('
  mmmmmm   mmmmmm                                                                         
  ""##""   ##""""#m                                                                       
    ##     ##    ##  mm#####m   m#####m   m#####m  ##m####m  ##m####m   m####m    ##m#### 
    ##     ######"   ##mmmm "  ##"    "   " mmm##  ##"   ##  ##"   ##  ##mmmm##   ##"     
    ##     ##         """"##m  ##        m##"""##  ##    ##  ##    ##  ##""""""   ##      
  mm##mm   ##        #mmmmm##  "##mmmm#  ##mmm###  ##    ##  ##    ##  "##mmmm#   ##      
  """"""   ""         """"""     """""    """" ""  ""    ""  ""    ""    """""    "" 
'
  # ----------------------------------------------------------------------------------------
  '
  _____ _____                                     
 |_   _|  __ \                                    
   | | | |__) |__  ___ __ _ _ __  _ __   ___ _ __ 
   | | |  ___/ __|/ __/ _` | `_ \| `_ \ / _ \ `__|
  _| |_| |   \__ \ (_| (_| | | | | | | |  __/ |   
 |_____|_|   |___/\___\__,_|_| |_|_| |_|\___|_|   
                                                  
                                                  
'
  # ----------------------------------------------------------------------------------------
  '

                                                                                                                                                               
                                                                                                                                                               
IIIIIIIIIIPPPPPPPPPPPPPPPPP                                                                                                                                    
I::::::::IP::::::::::::::::P                                                                                                                                   
I::::::::IP::::::PPPPPP:::::P                                                                                                                                  
II::::::IIPP:::::P     P:::::P                                                                                                                                 
  I::::I    P::::P     P:::::P   ssssssssss       cccccccccccccccc  aaaaaaaaaaaaa  nnnn  nnnnnnnn    nnnn  nnnnnnnn        eeeeeeeeeeee    rrrrr   rrrrrrrrr   
  I::::I    P::::P     P:::::P ss::::::::::s    cc:::::::::::::::c  a::::::::::::a n:::nn::::::::nn  n:::nn::::::::nn    ee::::::::::::ee  r::::rrr:::::::::r  
  I::::I    P::::PPPPPP:::::Pss:::::::::::::s  c:::::::::::::::::c  aaaaaaaaa:::::an::::::::::::::nn n::::::::::::::nn  e::::::eeeee:::::eer:::::::::::::::::r 
  I::::I    P:::::::::::::PP s::::::ssss:::::sc:::::::cccccc:::::c           a::::ann:::::::::::::::nnn:::::::::::::::ne::::::e     e:::::err::::::rrrrr::::::r
  I::::I    P::::PPPPPPPPP    s:::::s  ssssss c::::::c     ccccccc    aaaaaaa:::::a  n:::::nnnn:::::n  n:::::nnnn:::::ne:::::::eeeee::::::e r:::::r     r:::::r
  I::::I    P::::P              s::::::s      c:::::c               aa::::::::::::a  n::::n    n::::n  n::::n    n::::ne:::::::::::::::::e  r:::::r     rrrrrrr
  I::::I    P::::P                 s::::::s   c:::::c              a::::aaaa::::::a  n::::n    n::::n  n::::n    n::::ne::::::eeeeeeeeeee   r:::::r            
  I::::I    P::::P           ssssss   s:::::s c::::::c     ccccccca::::a    a:::::a  n::::n    n::::n  n::::n    n::::ne:::::::e            r:::::r            
II::::::IIPP::::::PP         s:::::ssss::::::sc:::::::cccccc:::::ca::::a    a:::::a  n::::n    n::::n  n::::n    n::::ne::::::::e           r:::::r            
I::::::::IP::::::::P         s::::::::::::::s  c:::::::::::::::::ca:::::aaaa::::::a  n::::n    n::::n  n::::n    n::::n e::::::::eeeeeeee   r:::::r            
I::::::::IP::::::::P          s:::::::::::ss    cc:::::::::::::::c a::::::::::aa:::a n::::n    n::::n  n::::n    n::::n  ee:::::::::::::e   r:::::r            
IIIIIIIIIIPPPPPPPPPP           sssssssssss        cccccccccccccccc  aaaaaaaaaa  aaaa nnnnnn    nnnnnn  nnnnnn    nnnnnn    eeeeeeeeeeeeee   rrrrrrr            
                                                                                                                                                               
                                                                                                                                                               
                                                                                                                                                               
                                                                                                                                                               
                                                                                                                                                               
                                                                                                                                                               
                                                                                                                                                               







'
  # ----------------------------------------------------------------------------------------

  '
_________ _______  _______  _______  _______  _        _        _______  _______ 
\__   __/(  ____ )(  ____ \(  ____ \(  ___  )( (    /|( (    /|(  ____ \(  ____ )
   ) (   | (    )|| (    \/| (    \/| (   ) ||  \  ( ||  \  ( || (    \/| (    )|
   | |   | (____)|| (_____ | |      | (___) ||   \ | ||   \ | || (__    | (____)|
   | |   |  _____)(_____  )| |      |  ___  || (\ \) || (\ \) ||  __)   |     __)
   | |   | (            ) || |      | (   ) || | \   || | \   || (      | (\ (   
___) (___| )      /\____) || (____/\| )   ( || )  \  || )  \  || (____/\| ) \ \__
\_______/|/       \_______)(_______/|/     \||/    )_)|/    )_)(_______/|/   \__/
                                                                                 






'

  # ----------------------------------------------------------------------------------------
  '

 ___   _______  _______  _______  _______  __    _  __    _  _______  ______   
|   | |       ||       ||       ||   _   ||  |  | ||  |  | ||       ||    _ |  
|   | |    _  ||  _____||       ||  |_|  ||   |_| ||   |_| ||    ___||   | ||  
|   | |   |_| || |_____ |       ||       ||       ||       ||   |___ |   |_||_ 
|   | |    ___||_____  ||      _||       ||  _    ||  _    ||    ___||    __  |
|   | |   |     _____| ||     |_ |   _   || | |   || | |   ||   |___ |   |  | |
|___| |___|    |_______||_______||__| |__||_|  |__||_|  |__||_______||___|  |_|
'

  # ----------------------------------------------------------------------------------------
  '







 _____ _____                             
|     |  _  |___ ___ ___ ___ ___ ___ ___ 
|-   -|   __|_ -|  _| .`|   |   | -_|  _|
|_____|__|  |___|___|__,|_|_|_|_|___|_|  
                                         

'

  # ----------------------------------------------------------------------------------------

  '
                                                      
                                                      
██ █████▄  ▄▄▄▄  ▄▄▄▄  ▄▄▄  ▄▄  ▄▄ ▄▄  ▄▄ ▄▄▄▄▄ ▄▄▄▄  
██ ██▄▄█▀ ███▄▄ ██▀▀▀ ██▀██ ███▄██ ███▄██ ██▄▄  ██▄█▄ 
██ ██     ▄▄██▀ ▀████ ██▀██ ██ ▀██ ██ ▀██ ██▄▄▄ ██ ██ 
                                                      
'

)

# Switch Case
# Funny thing where my name has a 4 in 28 chance to be something other than JustCallMeDullp :3
# The 0 is the first value in an array, so we use this with the array 'tag' to get the different tags.
rand() {


  echo "${die}"
  case ${bash d20} in
  1) echo 0 ;;
  17) echo 1 ;;
  18) echo 2 ;;
  19) echo 3 ;;
  20) echo 4 ;; 
  *)  echo "error" ;;

  esac
}
# Firs function
# Startp screen with color and animations. just looks nice
startup() {
  x=$(rand)
  clear
  echo ""
  echo -e "${cyan}${bigtext[($RANDOM % 7)]}${blank}"
  echo -e "${cyan}By: ${tag[(x)]} ${blank}"

  for x in {1..4}; do
    sleep 0.5
    echo "initializing content [${x}/4]"
  done
  sleep 1
  echo ""
  for y in {1..16}; do
    sleep 0.01
    echo "loading [${y}/16]"
  done
  sleep 2
}

# Like startup, it gives the user sometihng to look at while the script runs its magic.
welcome() {
  clear
  echo ""
  echo -e "${cyan}----------<<Welcome to IPscanner>>----------${blank}"
  echo -e "${green}Your address is:${blank}"
  echo -e "${red}$network${blank}"
  echo ""
  sleep 1.5
}

#This is the Scan etire network thingymajig
scan() {
  # Local variables are yanked from "what"
  local from=$1
  local to=$2
  total=$(( (to - from) +1 ))
  echo -e "Now searching for addresses on the network: ${purple}${network%.*}.x${blank}" #"\e[35${network%.*}\e[0m")
  sleep 2.5
  for ip in $( # We use the 'from' and 'to' from 'wait' to go trough the addresses the user wants
    seq "$from" "$to"
  ); do
    address="${network%.*}.${ip}" # this is to add the "ip" ('from' and 'to') variable to the "network" varable so we get something like 192.168.20.IP

    ping -c 1 -W 0.3 "${address}" >/dev/null 2>&1 #This is the thingy that pings an address and waits for a response

    if [ $? -eq 0 ]; then # this looks for adresses that did respond and prints the address with a nice green [up]
      if [ ${ip} -lt 10 ]; then
          echo -e "${address}${green}     [up]${blank}--------- ${count}/${total}"
      elif [ ${ip} -lt 100 ] && [ ${ip} -gt 9 ]; then
        echo -e "${address}${green}    [up]${blank}-------- ${count}/${total}"
      elif [ ${ip} -lt 255 ] && [ ${ip} -gt 99 ]; then
        echo -e "${address}${green}   [up]${blank}------- ${count}/${total}"
      fi

    elif [ $? -ne 0 ]; then # this looks for the addresses that did NOT respond, and prints the address with a nice red [down]
      if [ ${ip} -lt 10 ]; then
        echo -e "${address}${red}    [down]${blank}-------- ${count}/${total}"
      elif [ ${ip} -lt 100 ] && [ ${ip} -gt 9 ]; then
        echo -e "${address}${red}   [down]${blank}------- ${count}/${total}"
      elif [ ${ip} -lt 255 ] && [ ${ip} -gt 99 ]; then
        echo -e "${address}${red}  [down]${blank}------ ${count}/${total}"
      fi
    fi
      ((count += 1)) #this is just to show how many times the code ran. other words, how many adresses was pinged.
  done
  # print in yellow how many addresses was pinged
  echo -e "${yellow}Scanned $(( (ip)  )) adresses${blank}"
  count=1
}


# ----------------------------------------------------------------------------------------------------------------------------------
# And this is ofc, the first option.
first() {
 
  # myAddress=$(ip route get 1.1.1.1 | grep -oP "src \K\S+")
  # addr="${myAddress%.*}.${ip}"
  # ping -c 1 -W 0.1 "${addr}" >/dev/null 2>&1
  #
  # echo -e "${addr}${green}     [up]${blank}--------- ${ip}/254"
  # echo -e "${addr}${green}    [up]${blank}-------- ${ip}/254"
  # echo -e "${addr}${green}   [up]${blank}------- ${ip}/254"

  up=0
  echo ""
  echo "---------- Getting active IPs on the network ----------"
  echo ""
  myAddress=$(ip route get 1.1.1.1 | grep -oP "src \K\S+")
  for ip in {1..254}; do
    addr="${myAddress%.*}.${ip}"                  # make a full ip by removing the last set of numbers from your address and replace it with ${ip}
    ping -c 1 -W 0.1 "${addr}" >/dev/null 2>&1    # redirect both stdout and stderr to /dev/null

    if [ $? -eq 0 ]; then                         # if last task ($?) did not fail aka output IS 0 and not 1 or 2 then echo the address
      if [ ${ip} -lt 10 ]; then
        echo -e "${addr}${green}     [up]${blank}--------- ${ip}/254"
      elif [ ${ip} -lt 100 ] && [ ${ip} -gt 9 ]; then
        echo -e "${addr}${green}    [up]${blank}-------- ${ip}/254"
      elif [ ${ip} -lt 255 ] && [ ${ip} -gt 99 ]; then
        echo -e "${addr}${green}   [up]${blank}------- ${ip}/254"
      fi
    fi
    ((up+=1))
  done

  echo -e "Scanned ${yellow}${ip}${blank} addresses"
  echo -e "Of which ${yellow}${up}/${ip}${blank} were down"
  echo ""
  down=0
}

# ----------------------------------------------------------------------------------------------------------------------------------
# Then this must me... The second option
second() {
  down=0
  for ip in {1..254}; do
    address="${network%.*}.${ip}"                 # this is to add the 'ip' variable to the "network" varable so we get something like 192.168.20.IP
    ping -c 1 -W 0.1 "${address}" >/dev/null 2>&1 #This is the thingy that pings an address and waits for a response

    if [ $? -ne 0 ]; then # this looks for adresses that did NOT respond and prints the address with a red [down]
      if [ ${ip} -lt 10 ]; then
        echo -e "${address}${red}    [down]${blank}-------- ${ip}/254"
      elif [ ${ip} -lt 100 ] && [ ${ip} -gt 9 ]; then
        echo -e "${address}${red}   [down]${blank}------- ${ip}/254"
      elif [ ${ip} -lt 255 ] && [ ${ip} -gt 99 ]; then
        echo -e "${address}${red}  [down]${blank}------ ${ip}/254"
      fi
      ((down += 1))
    fi
  done
  echo -e "Scanned ${yellow}${ip}${blank} addresses"
  echo -e "Of which ${yellow}${down}/${ip}${blank} were down"
  down=0
  echo ""
}

# ----------------------------------------------------------------------------------------------------------------------------------
# Take a wild fucking guess.
third() {
  echo "cool, now. How many addresses do you want to see?"
  sleep 0.5
  echo -e "${network%.*}.${red}1-254${blank}"
  echo -e "Start at:"
  read from 
  echo -e "Stop at:"
  read to
  if [ $from -gt $to ]; then
    echo "Hey, no. You Can't do that. 'From' needs to be lower than 'to'"
    third
  elif [ $from -gt 254 ]; then
    echo "Can't be greater than 254"
    third
  elif [ $to -gt 254 ]; then
    echo "Can't be greater than 254"
    third
  else
    echo "$from..$to"  # this just prints the options you chose
    scan "$from" "$to" # this starts the scan function and sends the 'from' and 'to' variable to run the scan the correct ammount of time
  fi
}

# ----------------------------------------------------------------------------------------------------------------------------------
# This is the options menu. Also known as "what" as in What am i gonna do rn.
what() {
  echo "What do you wish to do?"
  echo "
  1. Show all active IPs
  2. Show all inactive IPs
  3. Scan range
  4. Exit
  "
  echo "enter [1-4]:"
  read  choice                 # This uses "-p" for ptomt. so that the string and the input is on the same line
  if ! [[ ${choice} =~ ^[1-4] ]]; then # check if the choice is NOT a number between 1 and 3
    clear
    echo -e "${bold}Not an option. Select [1-4]${normal}"
    what
  fi

  # Here we call the magic we gave the options
  if [ ${choice} -eq 1 ]; then
    first
    what
  elif [ ${choice} -eq 2 ]; then
    second
    what
  elif [ ${choice} -eq 3 ]; then
    third
    what
  elif [ ${choice} -eq 4 ]; then
    clear
    bash cls.sh
    exit
  fi
}

# This is where we start the program, and the order we do so in.
startup
welcome
wait
what
wait
